---
namespace: exo
name: apparmor
version: 1.0.0
readme: README.md

authors:
  - John Bakker

description: >-
  Ansible collection providing AppArmor utilities, modules, and roles.
  This collection contains custom modules and a role for managing AppArmor profiles
  in a modular and reusable way, including fragment collection, merging, and loading.

license:
  - MIT

tags:
  - apparmor
  - security
  - linux
  - system
  - hardening

repository: https://github.com/john-bakker/apparmor

dependencies: {}

